### ISSUE TITLE
Work on image output

### ISSUE THREAD

**Issue by kevingrillet** [kevingrillet/AFKArena-LabHelper#5]
Better image output to be ready to push on Reddit ;)
- [x] Title
- [x] Date
- [x] Tags (reddit/github)
- [x] Bigger legend
- [x] White mode
- [x] Toogle legend
- [x] Original colors

**Comment by Zebiano** [comment]
The output file already looks pretty sick, thank you very much for this! Here are a few things I've thought of:

1. Do you think it's possible to make the legend a bit bigger? I feel like it's difficult to read.
2. Did you use the same colors as the ones we use? I can send you the hex values if you want. 
3. I noticed the legend has different names. I feel like they are less intuitive.
4. The GitHub shortlink, didn't you want to make it easily memorizable?

**Comment by kevingrillet** [comment]
> 1. Do you think it's possible to make the legend a bit bigger? I feel like it's difficult to read.

Yep, possible, I'll experiment things later this week

> 2. Did you use the same colors as the ones we use? I can send you the hex values if you want.

I'm lazy, so it's CSS colors: <https://www.w3schools.com/cssref/css_colors.asp>
But yep, it's possible to use yours, the biggest difference is that I'm using dark background...

> 3. I noticed the legend has different names. I feel like they are less intuitive.

I'm using the in game names, so to me it's intuitive 😉 
But since not everybody knows about them ^^

> 4. The GitHub shortlink, didn't you want to make it easily memorizable?

I'all add it later: <https://git.io/LabPathHelper>

**Comment by Zebiano** [comment]
I see. Well, in the end I will probably run a tweaked version of this locally on a server anyways, and there I can change little details like not having a dark background and colors, etc. So so far, this seems really cool!

**Comment by kevingrillet** [comment]
For colors, I think a toogle in a corner and play with a new class will be enough to change every color.
And we could do the same for the names ^^

**Comment by kevingrillet** [comment]
> 1. Do you think it's possible to make the legend a bit bigger? I feel like it's difficult to read.

✔️ Did make it a bit bigger, tell me if you want more.

> 2. Did you use the same colors as the ones we use? I can send you the hex values if you want.

👍 You can give me your colors for the white mode

> 3. I noticed the legend has different names. I feel like they are less intuitive.

✔️ Toogle possible

> 4. The GitHub shortlink, didn't you want to make it easily memorizable?

✔️ Done

**Comment by Zebiano** [comment]
I'll try and get some colors tomorrow if I have the time!

**Comment by Zebiano** [comment]
General:
```
Hero Res: #fe3cbe
Fountain: #99d7ea
Wagon: #212e8e
Roamer: #654321
Easy camps: #c9a7a7
Medium/Hard camps: #f01b20
Legendary relic/Boss: #fec80a
```
Dismal Maze:
```
Divine fountain: #f26f29
Witch's den: #845cec
```
Arcane Lab:
```
Wrizz: #000000
```

**Comment by kevingrillet** [comment]
Done ;)
